enableTransparentWorkspaces: false

initFields:
  version: 0.1.0-0
  $schema: "https://json.schemastore.org/package"
  license: MIT
  type: module

initScope: yarnpkg

nodeLinker: node-modules

logFilters:
  # Suppress peerDependencies warnings
  - level: discard
    code: YN0002
  # - level: discard
  #   code: YN0060
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
#     spec: '@yarnpkg/plugin-constraints'
#   - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#     spec: '@yarnpkg/plugin-interactive-tools'
#   - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#     spec: '@yarnpkg/plugin-version'
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: '@yarnpkg/plugin-workspace-tools'

# yarnPath: .yarn/releases/yarn-3.2.1.cjs
