name: Deploy to Firebase Hosting Beta
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: set version 3.2.2
      - name: install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_HUB_47EAA }}"
          expires: 7d
          channelId: beta
          projectId: game-hub-47eaa
