name: Deploy to Firebase Hosting Live
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: set version 3.2.2
      - name: install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile
      - name: build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: run build
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_HUB_47EAA }}"
          channelId: live
          projectId: game-hub-47eaa
